version: '3.8'

services:
  db:
    image: postgres:17
    container_name: twitter-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foka
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - twitter-network

  backend:
    build:
      context: ./backend
    container_name: twitter-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:foka@db:5432/twitter
    depends_on:
      - db
    networks:
      - twitter-network

  frontend:
    build:
      context: ./frontend
    container_name: twitter-frontend
    ports:
      - "3000:80"
    networks:
      - twitter-network

volumes:
  postgres_data:

networks:
  twitter-network:
    driver: bridge
